prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: "anomaly-detection"
        scrape_interval: 10s
        static_configs:
          - targets:
            - "anomaly-detection.default.svc.cluster.local:8000"
